on:
  workflow_call:
    inputs:
      version:
        type: string
        required: false
      path:
        type: string
        default: "."
        required: false
      cache:
        type: string
        default: "true"
        required: false
      token:
        type: string
        default: "${{ github.token }}"
        required: false

jobs:
  test-env:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Create manifest file
      run: |
        cat > ${{ inputs.path }}/aftman.toml << EOF
        [tools]
        selene = "Kampfkarren/selene@0.25.0"
        stylua = "JohnnyMorganz/stylua@0.18.2"
        rojo = "rojo-rbx/rojo@7.3.0"
        EOF
      shell: bash

    - name: Run setup-aftman
      uses: ./
      with:
        version: ${{ inputs.version }}
        path: ${{ inputs.path }}
        cache: ${{ inputs.cache }}
        token: ${{ inputs.token }}

    - name: Verify executables in PATH on bash
      run: |
        command -v selene
        command -v stylua
        command -v rojo
      shell: bash

    - name: Verify executables in PATH on pwsh
      run: |
        Get-Command "selene"
        Get-Command "stylua"
        Get-Command "rojo"
      shell: pwsh
